### ISSUE TITLE
Meta Description is added after the SEO Extension one's

### ISSUE THREAD

**Issue by ramesh-dada** [justoverclockl/flarum-ext-keywords#10]
Meta Description is added after the SEO Extension one's but search engine always prefers the first one
![image](https://user-images.githubusercontent.com/75124237/127485571-c6c75329-efa4-402a-9f8c-07e5528b7be1.png)

**Comment by justoverclockl** [comment]
You can find multiple article about multiple meta description content, is allowed and secure.

**Comment by ramesh-dada** [comment]
Hello @justoverclockl Thanks for letting me know but I got to know that search engine always prefers the first meta tag if there are duplicates so maybe by checking source of v17 Seo you can override it.
