### ISSUE TITLE
v1.9.2 : Breaks Glossary Page on Reload

### ISSUE THREAD

**Issue by ramesh-dada** [justoverclockl/flarum-ext-keywords#9]
When I go to glossary page from forum nav the page loads without any problem but when I go to the glossary page directly by reloading my browser or by clicking link from somewhere else then the page is broken without css and the below errors are shown in console:
![image](https://user-images.githubusercontent.com/75124237/127484787-83627f14-dca7-4b09-9b06-5df20fd34d73.png)

**Comment by justoverclockl** [comment]
i can't reproduce this on flarum.it so must be a conflict with another extension. setSelectedTheme.js is not an error caused by keyword extension.

**Comment by ramesh-dada** [comment]
Thanks 👍 I got to know that it was caused by fof night mode. I disabled it work like a pro now.

**Comment by ramesh-dada** [comment]
@justoverclockl Will you update this to support fof night mode or not?

**Comment by justoverclockl** [comment]
This error is not caused from my extension. So is the other one tha t need to be updated
